theme: jekyll-theme-midnight
title: Hackystat
description: A framework for collection, analysis, visualization, interpretation, annotation, and dissemination of software development process and product data.